@extends('front.layouts.login')

@section('title', 'Login')

@section('content')

<style>
    .email_auth {
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
        width: 45%;
        justify-content: center;
        margin: 0 auto; 
    }
    .enter_procced_code{
        height: 55px;
        border-radius: 10px;
    }
    .btn.btn-lg.btn-success.btn-block {
        margin-top: 20px;
    }
    @media screen and (max-width: 667px) {
        .email_auth {
            width: 90%;
        }
    }
</style>

    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper email_auth">
        <div class="animate form login_form">
          <section class="login_content">

              {!! Form::open( ['url' => ['google/auth'], 'method' => 'POST', 'class' => 'form-horizontal form-label-left', 'role' => 'form']) !!}

                  <div style="display: none;">
                      <label>Your Secret Key</label>
                      <input type="text" id="secret" name="secret" placeholder="Secret key" class="enter_procced_code" value="<?php echo $secret; ?>" required="required" />
                      <?php if ($errors->has('secret')) { ?>
                      <br /><span class="error"><?php echo $errors->first('secret'); ?></span>
                      <?php } ?>
                  </div>

                  <?php if( !is_null($qrUrl) ){ ?>
                  <div>
                      <img src="<?php echo $qrUrl; ?>">
                  </div>
                  <?php } ?>

              @if ( $errors->count() )
                  <div class="alert alert-danger">
                      {!! implode('<br />', $errors->all()) !!}
                  </div>
              @endif
                  <div>
                      <label>Verification Code</label>
                      <input type="text" id="code" name="code" placeholder="Google Verification Code" required="required"  class="form-control" />
                      <?php if ($errors->has('code')) { ?>
                      <br /><span class="error"><?php echo $errors->first('code'); ?></span>
                      <?php } ?>
                  </div>

                  <label>
                      <input type="checkbox" id="is_trusted" name="is_trusted"  />
                      Trusted for 30 days
                  </label>
                  <br><br>


                  <?php if( !is_null($qrUrl) ){ ?>

                  <p>Downlaod Google Authenticator App on your device. Install the application and create a new account by scanning the QR code. Enter the Verification Code generated by Google App in "Verification Code" field and submit!.  </p>

                  <?php }else{ ?>

                  <p> Enter the Verification Code generated by Google Authenticator App in "Verification Code" field and submit!.  </p>

                  <?php } ?>

                  <input type="hidden" name='email' value="<?php echo $email ?>"></input>

                  <input type="hidden" name='key' value="<?php echo $key ?>"></input>

                  <div>
                      <button type="submit" class="btn btn-lg btn-success btn-block">Submit</button>
                  </div>



              {!! Form::close() !!}
                    </section>
					</div>
					</div>
					</div>

@endsection
